kijaniStore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('store_cart.urls', namespace='store_cart')),
    path('', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Kijani Grocery Store'  
admin.site.index_title = 'Grocery admin area' 
admin.site.site_title = 'Kijani Grocery Store Administration'

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path("create_order/", views.create_order, name='create_order'),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='products'),
    path('<slug:category_slug>/', views.product_list, name='products_sorted_with_category'),
    path('<int:id>/<slug:product_slug>/', views.product, name='product'),
]

store_cart/urls.py
from django.urls import path

from . import views

app_name = 'store_cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_items_to_cart, name='add_items_to_cart'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove_item_from_cart'),
]

store_cart/models.py
from django.db import models

store_cart/forms.py
from django import forms
from django.forms.fields import BooleanField

QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 50)]



class AddProductToCartForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

store_cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import StoreCart
from .forms import AddProductToCartForm



@require_POST
def add_items_to_cart(request, product_id):
    cart = StoreCart(request)
    product = get_object_or_404(Product, id=product_id)
    form = AddProductToCartForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.addItems(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('store_cart:cart_detail')


@require_POST
def remove_from_cart(request, product_id):
    cart = StoreCart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove_product(product)
    return redirect('store_cart:cart_detail')


def cart_detail(request):
    cart = StoreCart(request)
    for item in cart:
        item['update_quantity_form'] = AddProductToCartForm(initial={'quantity': item['quantity'], 'override':True})
    return render(request, 'cart/detail.html', {'cart': cart})

store_cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Your shopping cart{% endblock title %}

{% block content %}
    <section class="store-cart">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-10">
                    <h1>Your shopping cart</h1>
                    <table class="table table-success table-borderless table-striped table-hover table-sm">
                        <thead>
                          <tr>
                            <th scope="col">Image</th>
                            <th scope="col">Product</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Update</th>
                            <th scope="col">Remove</th>
                            <th scope="col">Unit price</th>
                            <th scope="col">Price</th>
                          </tr>
                        </thead>
                        <tbody>
                            {% for item in cart %}
                                {% with product=item.product %}
                                    <tr class="table-active">
                                        <td class="w-25"><a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" class="img-fluid w-50" alt=""></a></td>
                                        <td>{{ product.product_name }}</td>
                                        <td>{{ item.quantity }}</td>
                                        <td>
                                            <form action="{% url 'store_cart:add_items_to_cart' product.id %}" method="post">{% csrf_token %}
                                                {{ item.update_quantity_form.quantity }}
                                                {{ item.update_quantity_form.override }}
                                                <input type="submit" class="btn btn-success ms-2" value="Update">
                                            </form>
                                        </td>
                                        <td>
                                            <form action="{% url 'store_cart:remove_item_from_cart' product.id %}" method="post">
                                                {% csrf_token %}
                                                <input type="submit" class="btn btn-danger ms-2" value="Remove">
                                            </form>    
                                        </td>
                                        <td>Ksh: {{ item.price }}</td>
                                        <td>Ksh: {{ item.total_price }}</td>
                                    </tr>
                                {% endwith %}
                            {% endfor %}
                          <tr>
                            <td>Total</td>
                            <td colspan="5"></td>
                            <td>Ksh: {{ cart.get_total_price }}</td>
                          </tr>
                        </tbody>
                      </table>
                      <p class="text-end">
                          <a href="{% url 'shop:products' %}" class="btn btn-success">Continue shopping</a>
                          <a href="{% url 'orders:create_order' %}" class="btn btn-success">Checkout</a>
                      </p>
                </div>
            </div>
        </div>
    </section>


{% endblock content %}