kijaniStore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('store_cart.urls', namespace='store_cart')),
    path('', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Kijani Grocery Store'  
admin.site.index_title = 'Grocery admin area' 
admin.site.site_title = 'Kijani Grocery Store Administration'

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='products'),
    path('<slug:category_slug>/', views.product_list, name='products_sorted_with_category'),
    path('<int:id>/<slug:product_slug>/', views.product, name='product'),
]

store_cart/urls.py
from django.urls import path

from . import views

app_name = 'store_cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_items_to_cart, name='add_items_to_cart'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove_item_from_cart'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>
    <link href="{% static 'fontawesome_free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block css %}

    {% endblock %}
    <title>
        {% block title %}
            Kijani Grocery Store
        {% endblock %}    
    </title>
</head>
<body>
    {% include 'nav.html' %}
    <div class="root">
   
        {% block content %}
    
    
        {% endblock %}
    </div>

    <footer class="footer bg-success" id="footer">
        <section class="footer">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-10 text-center">
                        <h5>&copy; Kijani Grocery Store</h5>
                    </div>
                </div>
            </div>
        </section>
    </footer>

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/gsap.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% block js %} 

    {% endblock %}
</body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-success">
    <div class="container">
      <a class="navbar-brand fw-bolder text-uppercase" href="{% url 'shop:products' %}">Kijani</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 fw-bold">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'shop:products' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About us</a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {% if category %} {{ category.category_name }}  {% else %} All {% endif %}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for categor in categories %}
                    <li class="{% if category.slug == categor.slug %} active fw-bolder text-danger {% endif %}"><a class="dropdown-item" href="{{ categor.get_absolute_url }}">{{ categor.category_name }}</a></li>
                {% endfor %}
            </ul>
          </li> 
        </ul>
        <ul class="navbar-nav mb-2 mb-lg-0 d-flex fw-bold"> 
            <li class="nav-item cart ms-auto my-2">
                {% with total_items=cart|length %}
                  {% if total_items %}
                    <span class="fw-bold">
                      <a href="{% url 'store_cart:cart_detail' %}">
                        <i class="fas fa-shopping-cart me-2 fa-2x"></i>
                      </a>
                      Ksh: {{ cart.get_total_price }}
                    </span>
                  {% else %}
                    <span class="fw-bold"><i class="fas fa-shopping-cart me-2 fa-2x"></i>$0.00</span>
                  {% endif %}
                {% endwith %}
            </li>
        </ul>
      </div>
    </div>
  </nav>